### ISSUE TITLE
impossoble ti flash any esp

### ISSUE THREAD

**Issue by djepsylon** [vr6syncro/Bambulab_Esp32_LEDController#6]
hi,
i ve tried to flash your program on my esp32, on esp8266mod, on d1 mini with esp8266mod and impossible to flash anyone!
i ve also tried to download your source code and compile it in arduino ide but i don't find one library, i have alredy the error for the file update.h is missig but, i don't find the corect library who is associated with ths file.
Is this in link with ota and websocket correct? soo why i can't flash any esp? i ve tryed with anther program for see if this is not a problem with my drivers or my computer but i can put WLED in all my esp with their website flasher, it proof this is a problem with your code i think, no?
can you help me please?

best regards and good work! it is a qood add on for x1

**Comment by vr6syncro** [comment]
First of all this project is ESP32 only. So no ESP8622 will work. Also if you download the source code you have to move all data in the scr folder to a folder what is named Bambulab_Esp32_LEDController for the Arduino IDE to work. The Update.h is a part of a libary that is missing as it seems. The Webflasher should work fine. Maybe your board is not supported or you have not installed the driver for it? It is hard to say because there are no more informations that you provide. I tested the Webflasher with a D1 Mini ESP32 and NODEMCU ESP32 and it worked fine. If you flash it with binarys yourself you have to use 4 files and set the offset to bootloader.bin 4096 - partitions.bin 32768 - boot_app0.bin 57344 - firmware.bin 65536. Maybe your board need a different offset but for my boards it was all the same.
[flash.zip](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/files/12840221/flash.zip)

**Comment by djepsylon** [comment]
hi, thanks a lot for you quickest answer
so if i understad well, my d1 mini with esp8266 is not compatble with the web flasher but i ve tested with a esp 32 wroom on a dev board and impossible to flash it too. well in arduino ide wat is the library associated to the update.h file? this is the only one missing. normally if i recompile for my esp8266 your program could work? correct? 
for my es32 wroom i give you a photo of the hardware i use for you can see and i give you photo of d1 mini esp8266 i use too
soo my knowlege about arduino ide is at the beggining state, can you help me for use your script with my esp8266 on my d1mini? i ave a lot of d1 esp8266 and i hve only one esp32wroom and i use it for another project
![20231008_213729](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/96573654/e5371a89-9b86-47e3-b242-4ef1074d6b52)
![20231008_213901](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/96573654/f01544e8-e0f1-4ebd-8cb7-133e14de1458)
![20231008_213854](https://github.com/vr6syncro/Bambulab_Esp32_LEDController/assets/96573654/7dfd0e55-c2ce-421d-b78d-b118ec7816d1)

**Comment by vr6syncro** [comment]
This ESP32 looks strange and i dont know this type of board. 
The ESP8622 is not supported and will not work!

Have you any log message while flashing?

The update.h is part of the espressif esp32 libary.

please try: https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html

You can also try using vs code with the platformio extension.
